### ISSUE TITLE
[FEATURE]: Add storybook for easy UI testing

### ISSUE THREAD

**Issue by AbhinavMV** [WebXDAO/hashi-react#1]
### Detailed description

Maybe we can add [storybook](https://storybook.js.org/docs/react/get-started/introduction)

### Context

It would make it easier
- display the components to users.
- help developers test the components.

### Additional information

Let me know everyone's thoughts on this. 😄 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MatteuSan** [comment]
sure thing. you want to take this one? @AbhinavMV

**Comment by AbhinavMV** [comment]
yeah sure will give it a try
